### ISSUE TITLE
TinyMCE is bloated and overkill for simple reddit-based forum

### ISSUE THREAD

**Issue by rkkautsar** [CapungCSUI/CuapCuap#16]
Consider using [Medium.js](http://jakiestfu.github.io/Medium.js/docs/#Demos) rich text editor for threads and partial editor for replies.

**Comment by rkkautsar** [comment]
Up.
http://jsfiddle.net/rkkautsar/fntag2au/2/

---

I can work on this if you agree that TinyMCE is too much for the forum

**Comment by aldifahrezi** [comment]
I think for thread contents, TinyMCE is rather suitable. Would be interesting if you could work on replies with Medium.js
